import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${inter.className}`}>
        <header className="">
          <Header />
        </header>
        <main className="flex-1 p-4">{children}</main>
        <footer className="">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
