import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import Locationcom from "@/app/clients/FetchLocation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = document.cookie.split('; ').find(row => row.startsWith('theme='))?.split('=')[1];
                if (theme) {
                  document.documentElement.classList.add(theme);
                } else {
                  document.documentElement.classList.add('light');
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`min-h-screen flex flex-col ${inter.className}`}>
        <header className="sticky top-0 z-50">
          <Header />
        </header>
        <main className="flex-1 min-h-screen-100 p-1">
          <Locationcom>{children}</Locationcom>
        </main>
        <footer className="">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
